### ISSUE TITLE
Default resources for Oscar instances

### ISSUE THREAD

**Issue by countable** [open-osp/open-osp#106]
4 cores and 20G of memory by default to prevent overruns due to memory leaks, etc

**Comment by countable** [comment]
See docker-compose limits, for this oscar service.

**Comment by ferdinandpolpol** [comment]
Was reading through docker compose limits and it seems we can only use cpu and memory limits in compose 2.x, otherwise we will be needing to use [swarm mode for compose 3.x ](https://docs.docker.com/compose/compose-file/#resources) (we are currently using 3.3). @countable do you think it's okay to move to compose 2.2 and do you think there are advantages/disadvantages of doing so OR should we continue with 3.x

**Comment by countable** [comment]
I see. Thanks for researching this @ferdinandpolpol . That's unfortunate, since swarm mode is a can of worms to deal with . Let's park this one for the moment and use other methods.
