### ISSUE TITLE
Running docker-compose generates error: stat ./build.sh: no such file or directory

### ISSUE THREAD

**Issue by shaunluttin** [open-osp/open-osp#19]
Steps to reproduce: 
```
git clone https://github.com/open-osp/open-osp.git
cd open-osp/
./deploy-release.sh
```
**Expected behavior**: Oscar becomes available at localhost.

**Actual behavior**:
```
Error response from daemon: OCI runtime create failed: container_linux.go:346: 
starting container process caused "exec: \"./build.sh\": stat ./build.sh: no such file 
or directory": unknown
```
The problem might be due to the non-existence of the `build.sh` file (though there is a `build-release.sh` file) that is specified on line `10` the `docker-compose.yml` file.

**Comment by countable** [comment]
Thanks for reporting this @shaunluttin, it seems I didn't see this problem before because i had the openosp docker image already cached locally. but in its absence it tries to build instead of pull. We need to get CI set up so robots can find these kind of things.

`doing docker pull openosp/open-osp` first fixes it. I've added this to the deploy script. I didn't think it was necessary to do this before, maybe it's changed or I just remember wrong :)
