### ISSUE TITLE
MySQL/MariaDB Configuration

### ISSUE THREAD

**Issue by warrendennis** [open-osp/open-osp#88]
The MySQL my.cnf configuration override file needs to be accessible and editable to authorized technicians.  This file is often used for tuning the MySQL database.  Each configuration file should be unique to each server install.  
It is not currently obvious how this file can be easily accessed.

**Comment by countable** [comment]
What is an example of tuning that applies only to one clinic, and not all clinics. We should avoid exposing any config options unless we are sure they will be used. That's a key to all this automation.

**Comment by warrendennis** [comment]
The my.cnf file is intended by MySQL to be exposed for various tuning settings. Locking it defeats its purpose.  It doesn’t need to be publicly exposed. 

Buffer / cache sizes as one example.

Dennis

**Comment by countable** [comment]
With my infrastructure hat on, I have to issue "hard disagree" here. The benefit of OpenOSP stack is it abstracts away the fact we even use MySQL (and not postgres, etc). It's one application. The principle of encapsulation and information-hiding says we should only expose what's explicitly needed, and not the entire config by default.

However, I can see that an on-prem installation might have different memory requirements. In this case, we should expose the minimum required settings as env vars. ie) MYSQL_SHARED_BUF_SIZE. in docker-compose.override.yml , and not expose the entire my.cnf. The problem with doing the latter is we now have to version a config file for every single instance of OpenOSP. The default must be static, and make only the settings we need dynamic.

Notably, oscar.properties is a glaring exception that I've allowed because we really do change a ton of settings there. In contrast, my.cnf settings usually apply to all instances and rarely apply to a single one, so we need to design accordingly.

Given infrastructure is my responsibility on the project, I'd like users to tell me "what" they need, not how to do it :)

**Comment by warrendennis** [comment]
Database tuning is one of the Open OSP service offerings.  Access to the my.cnf file is required for situations where specific database tuning is needed.  The most common options are: 

Key_buffer
Max_allowed_packet
Thread_stack
Thread_cache_size
Max_connections
Table_cache
Innodb_buffer
Slow query log
Query_cache_limit

etc...

my.cnf is not the main config file. It’s an override file for setting various user options.  These options will be different for each Oscar installation depending on the size and performance of the database. It is being used incorrectly in the current db docker images if it is considered a main configuration file.

BTW the my.cnf file for MySQL is a perfect example of proper encapsulation: https://mariadb.com/kb/en/configuring-mariadb-with-option-files/ <https://mariadb.com/kb/en/configuring-mariadb-with-option-files/>


This is what we need. Is there any way it can be done?

**Comment by countable** [comment]
this is supported, documented in the README
